apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chore-game
  namespace: chore-game
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - chore.yothman.com
      secretName: chore-game-tls
  rules:
    - host: chore.yothman.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chore-game
                port:
                  number: 80
