apiVersion: v1
kind: Secret
metadata:
  name: chore-game-secrets
  namespace: chore-game
type: Opaque
stringData:
  POSTGRES_PASSWORD: "Monet+19"
  DATABASE_URL: "postgresql://chore_user:Monet+19@postgres:5432/chore_game"
  JWT_SECRET: "replace-with-long-random-secret"
  ADMIN_USERNAME: "admin"
  ADMIN_PASSWORD: "monet+"

