apiVersion: v1
kind: Secret
metadata:
  name: chore-game-secrets
  namespace: chore-game
type: Opaque
stringData:
  POSTGRES_PASSWORD: "yothman"
  DATABASE_URL: "postgresql://chore_user:yothman@postgres:5432/chore_game"
  JWT_SECRET: "replace-with-long-random-secret"
  ADMIN_USERNAME: "admin"
  ADMIN_PASSWORD: "yothman98"
